version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nyunoshev/wmb:latest
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: mydatabase
      ENV: dev 
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
